---
- name: Configure IPV6 Addressing
  hosts: routers
  gather_facts: no

  tasks:
    - name: Configure interface
      ios_config:
        parents: "interface GigabitEthernet1"
        lines:
          - description IPv6 ADDRESS
          - ipV6 address 2001:db8:acad:1::1/64
          - ipv6 address fe80::1:1 link-local

    - name: Show IPv6 Interface brief
      ios_command:
        commands:
          - show ipv6 interface brief
      register: output

    - name: Save output ./ios_configurations/
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "ios_configuration/IPV6_output {{ inventory_hostname }}.txt"